@startuml
!theme minty
skinparam PackageBackgroundColor transparent
skinparam FolderBackgroundColor transparent
skinparam ActorBackgroundColor transparent
skinparam ActorFontColor black
skinparam EntityBackgroundColor transparent
skinparam EntityFontColor black
skinparam ControlBackgroundColor transparent
skinparam ControlFontColor black
skinparam BoundaryBackgroundColor transparent
skinparam BoundaryFontColor black
skinparam ArrowFontColor black
skinparam FolderFontColor black
skinparam ArrowThickness 1

actor "Client"

left to right direction
package {
  boundary "Server API" 
  control "Accept Loop"
  control "Alerts Monitor"
  control "Client Handler"
  entity " Metrics\nManager" as MetricsManager
  entity "    File\nManager" as FileManager
  folder logs [
    <metric-id>.log
    ....
    <metric-id>.log
    ....
    <metric-id>.log
  ] 
}


Client --> [Server API]
[Server API] --> "1" [Accept Loop]
[Server API] -right-> "1" [Alerts Monitor]
[Accept Loop] "0..N" --> [Client Handler]
[Client Handler] --> [MetricsManager]
[Alerts Monitor] --> [MetricsManager]
[MetricsManager] --> [FileManager]
[FileManager] " " --> "//RWLock//" [logs]


@enduml
