@startuml
!theme sandstone
skinparam swimlanetitlefontcolor black
skinparam SwimlaneTitleBackgroundColor #EEE

|Client|
|Feeder|
|Server|
|Graph|

|Feeder|
start
:Read & Send Line;
|Server|
:Dispatch to Graph;
|Graph|
:Process & Send Metrics;
|Server|
:Collect Metrics;
stop

|Client|
start
:Ask for metrics;
|Server|
:Return everything collected;
|Client|
stop

@enduml

