@startuml
!theme minty

skinparam PartitionFontColor black
skinparam LegendFontColor black
skinparam ArrowFontColor black
skinparam NoteBackgroundColor lemonchiffon
skinparam NoteFontColor black
skinparam backgroundColor white

skinparam ArrowFontColor black
skinparam NoteBackgroundColor lemonchiffon
skinparam NoteFontColor black
skinparam backgroundColor white
skinparam ConditionEndStyle hline

como un cliente pide una metrica

@enduml

