@startuml
!theme minty

skinparam PartitionFontColor black
skinparam LegendFontColor black
skinparam ArrowFontColor black
skinparam NoteBackgroundColor lemonchiffon
skinparam NoteFontColor black
skinparam legendbackgroundcolor transparent
skinparam ConditionEndStyle hline

partition "Allow the user to download the highest sentiment post" {
  start
  -> ...( type,...,id )...;
  :Source;
  if (type) then (post)
    :PostsWorker;
    note left
      grab url
      (and don't lose the id!)
    endnote
  else (comment)
    :CommentsWorker;
    note right
      get post_id
      from other attrs
    endnote
    -> ...( post_id,sentiment )...;
    #ff8662 :SentimentAverager;
    note right
      aggregate by post
    endnote
    -> ...( post_id,sentiment )...;
    #ff8662 :Filterer;
    note right
      keep track of the max sentiment_avg
      only push out if sentiment_avg > max
    endnote
  endif
  -> --> ...( id, url )... \n ( id, sentiment_avg ) <--;
  #ff8662 :Joiner<
    note left
      join by id, so that we can have
      (id,url,sentiment_avg)
    endnote
  -> ( url );
  :ImageStreamer;
  -> bytes(url);
  stop

  legend bottom right
      |= |Worker Type|
      |<#56cc9d>| Stateless & Scalable|
      |<#ff8662>| Stateful & Unique|
  endlegend
}

@enduml


