@startuml
!theme sandstone

skinparam PartitionFontColor black
skinparam PartitionBorderColor black
skinparam ArrowFontColor black
skinparam LegendFontColor black
skinparam legendbackgroundcolor transparent
skinparam NoteBackgroundColor lemonchiffon
skinparam NoteFontColor black

partition "Return the average post score" {
  start
  -> ...( id,...,score )...;
  :PostsWorker;
  note left
    grab the post score
  endnote
  -> ...( score )...;
  #f47c3c :ScoreAverager; 
  note right
    keep track of count and sum
  endnote
  -> ( score_avg );
  stop

  legend bottom right
      |= |Worker Type|
      |<#325d88>| Stateless & Scalable|
      |<#f47c3c>| Stateful & Unique|
  endlegend
}
@enduml
