@startuml
!theme minty

skinparam PartitionFontColor black
skinparam LegendFontColor black
skinparam ArrowFontColor black
skinparam NoteBackgroundColor lemonchiffon
skinparam NoteFontColor black
skinparam legendbackgroundcolor transparent

partition "Return the average post score" {
  start
  -> ...( id,...,score )...;
  :PostsWorker;
  note left
    grab the post score
  endnote
  -> ...( score )...;
  #ff8662 :ScoreAverager; 
  note right
    keep track of count and sum
  endnote
  -> ( score_avg );
  stop

  legend bottom right
      |= |Worker Type|
      |<#56cc9d>| Stateless & Scalable|
      |<#ff8662>| Stateful & Unique|
  endlegend
}
@enduml
