@startuml
!theme minty

skinparam PartitionFontColor black
skinparam LegendFontColor black
skinparam ArrowFontColor black
skinparam NoteBackgroundColor lemonchiffon
skinparam NoteFontColor black
skinparam backgroundColor white

skinparam ArrowFontColor black
skinparam NoteBackgroundColor lemonchiffon
skinparam NoteFontColor black
skinparam backgroundColor white
skinparam ConditionEndStyle hline

#solo describir el grafo y mostrar en cuales puede haber muchos y en cuales no
#que sea un 1:1 del super dag


@enduml

