@startuml
!theme minty
skinparam PackageBackgroundColor transparent
skinparam FolderBackgroundColor transparent
skinparam ActorBackgroundColor transparent
skinparam ActorFontColor black
skinparam EntityBackgroundColor transparent
skinparam EntityFontColor black
skinparam ControlBackgroundColor transparent
skinparam ControlFontColor black
skinparam BoundaryBackgroundColor transparent
skinparam BoundaryFontColor black
skinparam ArrowFontColor black
skinparam FolderFontColor black
skinparam ArrowThickness 1

actor "Client"
actor "Server"

Client -> Server
@enduml
