@startuml
!theme sandstone

skinparam PartitionFontColor black
skinparam PartitionBorderColor black
skinparam ArrowFontColor black
skinparam LegendFontColor black
skinparam legendbackgroundcolor transparent
skinparam ConditionEndStyle hline
skinparam NoteBackgroundColor lemonchiffon
skinparam NoteFontColor black
skinparam filebordercolor transparent
skinparam filebackgroundcolor transparent

file {
  interface start #black [
  ]
  stack Collector #d9534f [
  Collector
  ]
  card Source #325d88
  card PostsWorker #325d88
  card CommentsWorker #325d88
  card ImageStreamer #325d88
  card ScoreAverager #f47c3c
  card SentimentAverager #f47c3c
  hexagon Joiner #f47c3c
  card Filterer #f47c3c
  card StudentDecider #f47c3c

  start -down-> Source: post or comment
  Source -down-> PostsWorker: post
  Source -down-> CommentsWorker: comment
  PostsWorker -down-> ScoreAverager: post score
  CommentsWorker -down-> SentimentAverager: Post id\nComment Sentiment
  CommentsWorker -down-> StudentDecider: Post id\nComment Body
  PostsWorker -down-> Joiner: Post w/\nmetadata
  SentimentAverager -down-> Joiner: Posts w/\navg sentiment
  StudentDecider -down-> Joiner: Posts w/\nstudent keywords
  Joiner -down-> Filterer: Posts w/\nfull metadata
  Filterer -down-> ImageStreamer
  ScoreAverager --down--> Filterer: Post Score Average
  ScoreAverager --down--> Collector: Metric: Post\nScore Average
  ImageStreamer -down-> Collector: Metric: High\nSentiment Meme
  Filterer --down--> Collector: Metric: Student\nLiked URLs
}

legend bottom right
    |= |Worker Type|
    |<#325d88>| Stateless & Scalable|
    |<#f47c3c>| Stateful & Unique|
endlegend

@enduml
