@startuml
!theme sandstone

skinparam packagebackgroundcolor transparent
skinparam CloudBackgroundColor transparent
skinparam CloudBorderColor #29abe0
skinparam Cloudfontsize 16
skinparam CollectionsBackgroundColor #29abe0
skinparam actorbackgroundcolor transparent
skinparam actorfontcolor black
skinparam ArrowThickness 1
skinparam Packageborderthickness 1
skinparam filebackgroundcolor transparent
skinparam filefontcolor black
skinparam filebordercolor #29abe0


package "Graph" {
  collections nodes
  card Source
  Source -right-> nodes
}

actor User
file CSVs
cloud Feeder
CSVs -right-> Feeder
Feeder -up-> Source

package "Query" {
  card Client
  card Server
  Server <---right---> Client
}

nodes -up-> Server
Client --right--> User

@enduml

