@startuml
!theme minty

skinparam PartitionFontColor black
skinparam LegendFontColor black
skinparam ArrowFontColor black
skinparam NoteBackgroundColor lemonchiffon
skinparam NoteFontColor black
skinparam backgroundColor white

skinparam ArrowFontColor black
skinparam NoteBackgroundColor lemonchiffon
skinparam NoteFontColor black
skinparam backgroundColor white
skinparam ConditionEndStyle hline

partition "Return URLs of student-liked posts (w/good score)" {
  start
  -> ...( type,...,id )...;
  :Source;
  if (type) then (post)
    :PostsWorker;
    -> ...( id,score,permalink )...;
    #ff8662 :ScoreAverager; 
    note left
      only push out posts with 
      score greater than avg
    endnote
  else (comment)
    :CommentsWorker;
    -> ...( post_id,body )...;
   #ff8662 :StudentDecider;
    note right
      push student-related only
    endnote
  endif
    -> --> ...( id,permalink )... \n            ( id ) <--;
  #ff8662 :Joiner<
  -> (permalink);
  stop

  legend bottom right
      |= |Worker Type|
      |<#56cc9d>| Stateless & Scalable|
      |<#ff8662>| Stateful & Unique|
  endlegend
}

@enduml

