@startuml
!theme sandstone

skinparam PartitionFontColor black
skinparam PartitionBorderColor black
skinparam ArrowFontColor black
skinparam LegendFontColor black
skinparam legendbackgroundcolor transparent
skinparam ConditionEndStyle hline
skinparam NoteBackgroundColor lemonchiffon
skinparam NoteFontColor black

partition "Return URLs of student-liked posts (w/good score)" {
  start
  -> ...( type,...,id )...;
  :Source;
  if (type) then (post)
    :PostsWorker;
    -> ...( id,score,permalink )...;
    #f47c3c :ScoreAverager; 
    note left
      only push out posts with 
      score greater than avg
    endnote
  else (comment)
    :CommentsWorker;
    -> ...( post_id,body )...;
   #f47c3c :StudentDecider;
    note right
      push student-related only
    endnote
  endif
    -> --> ...( id,permalink )... \n            ( id ) <--;
  #f47c3c :Joiner<
  -> (permalink);
  stop

  legend bottom right
      |= |Worker Type|
      |<#325d88>| Stateless & Scalable|
      |<#f47c3c>| Stateful & Unique|
  endlegend
}

@enduml

