@startuml
!theme minty

skinparam rectanglebackgroundcolor transparent
skinparam rectanglefontcolor black
skinparam actorbackgroundcolor transparent
skinparam actorfontcolor black

left to right direction
actor "Client" as fc
rectangle Server {
  usecase "Average Post\nScore" as UC1
  usecase "High-sentiment\nimages" as UC2
  usecase "Student-liked\nposts" as UC3
  usecase "Future Metrics" as UC4
}
fc --> UC1
fc --> UC2
fc --> UC3
fc ..> UC4

@enduml
