version: '3'
services:
  server:
    image: server:latest
    networks:
      - testing_net
    volumes:
      - ./config.ini:/config.ini:ro
      - ./logs:/logs

  informe:
    image: informe:latest
    volumes:
      - ./informe.pdf:/informe.pdf

  client:
    image: client:latest
    networks:
      - testing_net
    volumes:
      - ./config.ini:/config.ini:ro
    depends_on:
      - server
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: ${CLIENT_REPLICAS:-1}

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
