version: '3'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - ./server/config:/config:ro

  nc-test:
    container_name: nc-test
    image: nc-test:latest
    entrypoint: /bin/sh /test.sh
    networks:
      - testing_net
    profiles:
      - test
    depends_on:
      - server

  # https://stackoverflow.com/a/69824975
  client1: &client
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config:/build/config:ro

  ### Append to me, programatically! (probably, with sed)

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
