version: '3'
services:
  feeder:
    image: feeder:latest
    networks:
      - testing_net
    volumes:
      - ./config.ini:/config.ini:ro
      - ./data:/data
    environment:
      - TEST_LINES=50
    profiles: ["feeder"]

  base_node: &base_node
    image: node:latest
    networks:
      - testing_net
    profiles: ["graph"]
    volumes:
      - ./config.ini:/config.ini:ro

  posts_worker:
    <<: *base_node
    environment:
      - NODE_TYPE=posts_worker
    deploy:
      mode: replicated
      replicas: ${POSTS_WORKERS:-1}

  comments_worker:
    <<: *base_node
    environment:
      - NODE_TYPE=comments_worker
    deploy:
      mode: replicated
      replicas: ${COMMENTS_WORKERS:-1}

  source:
    <<: *base_node
    environment:
      - NODE_TYPE=source

  collector:
    <<: *base_node
    environment:
      - NODE_TYPE=collector
    depends_on:
      - posts_worker

  comments_sentiment_worker:
    <<: *base_node
    environment:
      - NODE_TYPE=comments_sentiment_worker
    depends_on:
      - comments_worker

  comments_sentiment_max:
    <<: *base_node
    environment:
      - NODE_TYPE=comments_sentiment_max
    depends_on:
      - comments_sentiment_worker


  server:
    image: server:latest
    networks:
      - testing_net
    volumes:
      - ./config.ini:/config.ini:ro
    profiles: ["query"]

  client:
    image: client:latest
    networks:
      - testing_net
    volumes:
      - ./config.ini:/config.ini:ro
    profiles: ["query"]
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
