version: '3'
services:
  feeder:
    image: feeder:latest
    networks:
      - testing_net
    volumes:
      - ./config.ini:/config.ini:ro
      - ./data:/data:ro
    environment:
      - TEST_LINES=0
    profiles: ["feeder"]

  base_node: &base_node
    image: node:latest
    networks:
      - testing_net
    profiles: ["graph"]
    volumes:
      - ./config.ini:/config.ini:ro

  posts_worker:
    <<: *base_node
    environment:
      - NODE_TYPE=posts_worker
    deploy:
      mode: replicated
      replicas: ${POSTS_WORKERS:-1}

  comments_worker:
    <<: *base_node
    environment:
      - NODE_TYPE=comments_worker
    deploy:
      mode: replicated
      replicas: ${COMMENTS_WORKERS:-1}

  source:
    <<: *base_node
    environment:
      - NODE_TYPE=source

  posts_averager:
    <<: *base_node
    environment:
      - NODE_TYPE=posts_averager
    depends_on:
      - posts_worker

  posts_filter:
    <<: *base_node
    environment:
      - NODE_TYPE=posts_filter
    depends_on:
      - posts_averager

  comments_averager:
    <<: *base_node
    environment:
      - NODE_TYPE=comments_averager
    depends_on:
      - comments_worker

  posts_max_sentiment:
    <<: *base_node
    environment:
      - NODE_TYPE=posts_max_sentiment
    depends_on:
      - comments_averager

  image_streamer:
    <<: *base_node
    environment:
      - NODE_TYPE=image_streamer
    depends_on:
      - posts_max_sentiment

  joiner:
    <<: *base_node
    environment:
      - NODE_TYPE=joiner
    depends_on:
      - posts_max_sentiment

  server:
    image: server:latest
    networks:
      - testing_net
    volumes:
      - ./config.ini:/config.ini:ro
    profiles: ["query"]

  client:
    image: client:latest
    networks:
      - testing_net
    volumes:
      - ./config.ini:/config.ini:ro
      - ./memes:/memes
    profiles: ["query"]
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
