version: '3'
services:
  server:
    image: server:latest
    networks:
      - testing_net
    volumes:
      - ./config.ini:/config.ini:ro
    depends_on:
      - posts_worker

  feeder:
    image: feeder:latest
    networks:
      - testing_net
    volumes:
      - ./config.ini:/config.ini:ro
      - ./data:/data
    depends_on:
      - server
    environment:
      - TEST_LINES=5

  base_node: &base_node
    image: node:latest
    networks:
      - testing_net
    volumes:
      - ./config.ini:/config.ini:ro

  posts_worker:
    <<: *base_node
    environment:
      - NODE_TYPE=posts_worker
    deploy:
      mode: replicated
      replicas: ${POSTS_WORKERS:-1}

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
